[phases.setup]
nixPkgs = ["nodejs_20", "python3", "pkg-config", "gcc"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "NODE_ENV=production npx tsx server.ts"
